### ISSUE TITLE
clean up dash folder

### ISSUE THREAD

**Issue by bchampp** [bchampp/Q20#12]
@ethanmpeterson I like how you structured the can folder, it would be nice to have a similar structure for the dash folder

**Comment by bchampp** [comment]
Sim stuff can be in its own folder, same with dyno stuff? 19 will go into the Q19 repository on the gitlab

**Comment by ethanmpeterson** [comment]
@bchampp  Sounds like a plan. I will organize the dash code as we did the CAN bus folder.

**Comment by llim1** [comment]
I think there's a decent amount of code in the dash folder that's either duplicate or garbage, too. After it's organized it might be a good idea to do a quick purge
